import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
  ArcElement
} from 'chart.js';
import { Bar, Pie } from 'react-chartjs-2';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import './App.css';

// Register ChartJS components
ChartJS.register(
  CategoryScale, LinearScale, BarElement, Title, Tooltip, Legend, ArcElement
);

function App() {
  // --- State ---
  const [showIntro, setShowIntro] = useState(true);
  const [authToken, setAuthToken] = useState(localStorage.getItem('authToken') || '');
  const [isLoggedIn, setIsLoggedIn] = useState(!!localStorage.getItem('authToken'));
  const [username, setUsername] = useState(localStorage.getItem('username') || '');
  
  const [isRegistering, setIsRegistering] = useState(false);
  const [password, setPassword] = useState('');
  
  const [file, setFile] = useState(null);
  const [data, setData] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState([]);

  // Refs for Charts to capture images
  const barChartRef = useRef(null);
  const pieChartRef = useRef(null);

  // --- Fetch History Logic ---
  const fetchHistory = async (token) => {
    if (!token) return;
    try {
      const res = await axios.get('https://chemvispro.onrender.com/api/upload/', {
        headers: { 'Authorization': `Token ${token}` }
      });
      setHistory(res.data.history);
    } catch (err) {
      console.error("Failed to fetch history", err);
      // If 401, token might be invalid
      if (err.response && err.response.status === 401) {
        handleLogout();
      }
    }
  };

  // --- Effect: Load history on mount or login ---
  useEffect(() => {
    if (isLoggedIn && authToken) {
      fetchHistory(authToken);
    }
  }, [isLoggedIn, authToken]);

  const handleAuth = async (e) => {
    e.preventDefault();
    setError('');
    if (!username || !password) { setError('Please enter both username and password.'); return; }

    const endpoint = isRegistering ? 'register/' : 'login/';
    const url = `https://chemvispro.onrender.com/api/${endpoint}`;

    try {
      const response = await axios.post(url, { username, password });
      if (response.status === 200) {
        const token = response.data.token;
        const user = response.data.username;
        
        // Save to storage
        localStorage.setItem('authToken', token);
        localStorage.setItem('username', user);

        // Update state
        setAuthToken(token);
        setIsLoggedIn(true);
        setUsername(user);
        setError('');
        
        // Explicitly fetch history immediately with the new token
        fetchHistory(token);
      }
    } catch (err) {
      if (err.response && err.response.data) {
        const msg = err.response.data.error || JSON.stringify(err.response.data);
        setError(`Error: ${msg}`);
      } else {
        setError('Connection to backend failed.');
      }
    }
  };

  const handleLogout = () => {
    setIsLoggedIn(false); setUsername(''); setPassword(''); setAuthToken('');
    setData([]); setStats(null); setHistory([]); setFile(null);
    setIsRegistering(false); setShowIntro(true);
    localStorage.removeItem('authToken'); localStorage.removeItem('username');
  };

  const loadHistoryItem = async (id) => {
    setLoading(true);
    try {
      const res = await axios.get(`https://chemvispro.onrender.com/api/history/${id}/`, {
         headers: { 'Authorization': `Token ${authToken}` }
      });
      setData(res.data.data);
      setStats(res.data.stats);
      setError('');
    } catch (err) {
      setError('Failed to load history item.');
    }
    setLoading(false);
  };

  const handleFileChange = (e) => { setFile(e.target.files[0]); setError(''); };

  const handleUpload = async () => {
    if (!file) { setError('Please select a CSV file first.'); return; }
    const formData = new FormData();
    formData.append('file', file);
    setLoading(true);
    try {
      const res = await axios.post('https://chemvispro.onrender.com/api/upload/', formData, {
        headers: { 'Content-Type': 'multipart/form-data', 'Authorization': `Token ${authToken}` }
      });
      setData(res.data.data);
      setStats(res.data.stats);
      setHistory(res.data.history);
      setError('');
    } catch (err) {
      if (err.response && err.response.status === 403) setError('Session expired. Please logout.');
      else setError('Upload failed.');
    }
    setLoading(false);
  };

  // --- PDF Generator with Charts ---
  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(18);
    doc.text("Chemical Equipment Report", 14, 20);
    doc.setFontSize(10);
    doc.text(`Generated by: ${username} on ${new Date().toLocaleString()}`, 14, 28);
    
    // Stats
    let yPos = 40;
    if (stats) {
      doc.setFontSize(12);
      doc.text(`Total Count: ${stats.total_count}`, 14, yPos);
      doc.text(`Avg Pressure: ${stats.avg_pressure} psi`, 80, yPos);
      doc.text(`Avg Temperature: ${stats.avg_temp} C`, 150, yPos);
      yPos += 15;
    }

    // Capture Charts
    if (barChartRef.current && pieChartRef.current) {
        const barURL = barChartRef.current.toBase64Image();
        const pieURL = pieChartRef.current.toBase64Image();

        // Add Charts to PDF
        doc.addImage(barURL, 'PNG', 15, yPos, 90, 50);
        doc.addImage(pieURL, 'PNG', 115, yPos, 80, 50);
        yPos += 60; // Move down for table
    }
    
    // Data Table
    const tableColumn = ["Name", "Type", "Pressure", "Temp", "Status"];
    const tableRows = [];
    data.forEach(row => {
      tableRows.push([
        row['Equipment Name'] || row.name,
        row['Type'] || row.type,
        row['Pressure'] || row.pressure,
        row['Temperature'] || row.temp,
        row.Status || 'UNKNOWN'
      ]);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: yPos,
    });

    doc.save("equipment_report_with_charts.pdf");
  };

  const barChartData = {
    labels: data.map(d => d['Equipment Name'] || d.name),
    datasets: [
      { label: 'Pressure (psi)', data: data.map(d => d['Pressure'] || d.pressure), backgroundColor: 'rgba(53, 162, 235, 0.5)' },
      { label: 'Temperature (C)', data: data.map(d => d['Temperature'] || d.temp), backgroundColor: 'rgba(255, 99, 132, 0.5)' },
    ],
  };

  const getPieData = () => {
    if (!stats || !stats.type_distribution) return { labels: [], datasets: [] };
    return {
      labels: Object.keys(stats.type_distribution),
      datasets: [{
        data: Object.values(stats.type_distribution),
        backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0', '#9966FF'],
      }],
    };
  };

  const pieOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom' } } };

  if (showIntro) {
    return (
      <div className="intro-container">
        <div className="intro-content">
          <div className="logo-icon">⚗️</div>
          <h1>ChemVis Pro</h1>
          <h2>Chemical Equipment Parameter Visualizer</h2>
          <p className="intro-text">A comprehensive hybrid solution for monitoring, analyzing, and reporting on chemical equipment performance.</p>
          <button className="start-btn" onClick={() => setShowIntro(false)}>
            {isLoggedIn ? "Go to Dashboard" : "Login / Register"}
          </button>
        </div>
      </div>
    );
  }

  if (!isLoggedIn) {
    return (
      <div className="login-container">
        <div className="login-box">
          <h2>{isRegistering ? 'Create Account' : 'Welcome Back'}</h2>
          <form onSubmit={handleAuth}>
            <input type="text" placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} />
            <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />
            <button type="submit" style={{ backgroundColor: isRegistering ? '#27ae60' : '#3498db' }}>
              {isRegistering ? 'Create Account' : 'Login'}
            </button>
            <p style={{ marginTop: '15px', fontSize: '0.9rem', color: '#666' }}>
              {isRegistering ? "Already have account?" : "No account?"}
              <span onClick={() => { setIsRegistering(!isRegistering); setError(''); }} style={{ color: '#3498db', cursor: 'pointer', marginLeft: '5px', fontWeight: 'bold' }}>
                {isRegistering ? 'Login' : 'Register'}
              </span>
            </p>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="app-container">
      <header className="navbar">
        <h1>⚗️ ChemVis Pro</h1>
        <div style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
          <span style={{ fontSize: '0.9rem' }}>Welcome, <strong>{username}</strong></span>
          <button className="logout-btn" onClick={handleLogout}>Logout</button>
        </div>
      </header>

      <main className="main-content">
        <section className="controls">
          <div className="card upload-card">
            <h3>📂 Upload CSV</h3>
            <input type="file" onChange={handleFileChange} accept=".csv" />
            <button onClick={handleUpload} disabled={loading}>{loading ? 'Processing...' : 'Upload & Analyze'}</button>
            {error && <p className="error-text">{error}</p>}
          </div>
          <div className="card history-card">
            <h3>📜 History</h3>
            <ul className="history-list">
              {history.map((h, i) => (
                <li key={h.id || i} onClick={() => loadHistoryItem(h.id)} className="history-item">
                  <div style={{display:'flex', flexDirection:'column'}}>
                    <span className="file-name">{h.file_name}</span>
                    <span className="file-date">{new Date(h.uploaded_at).toLocaleDateString()}</span>
                  </div>
                </li>
              ))}
              {history.length === 0 && <small style={{color:'#999', fontStyle: 'italic', padding: '10px'}}>No history yet.</small>}
            </ul>
          </div>
        </section>

        <section className="analytics">
          {stats && (
            <div className="kpi-row">
              <div className="kpi-card"><h4>Total</h4><p>{stats.total_count}</p></div>
              <div className="kpi-card"><h4>Avg Pressure</h4><p>{stats.avg_pressure} <small>psi</small></p></div>
              <div className="kpi-card"><h4>Avg Temp</h4><p>{stats.avg_temp} <small>°C</small></p></div>
              <div className="kpi-card action-card" onClick={generatePDF}><h4>📄 Download Report</h4><p>With Charts</p></div>
            </div>
          )}

          {data.length > 0 ? (
            <div className="charts-grid">
              <div className="chart-card">
                <h4>Pressure vs Temperature</h4>
                {/* Ref attached here */}
                <Bar ref={barChartRef} data={barChartData} />
              </div>
              <div className="chart-card">
                <h4>Equipment Type Distribution</h4>
                <div className="pie-container" style={{ position: 'relative', height: '300px', width: '100%' }}>
                  {/* Ref attached here */}
                  <Pie ref={pieChartRef} data={getPieData()} options={pieOptions} />
                </div>
              </div>
            </div>
          ) : (
            <div className="empty-state"><p>Upload a CSV file to view analytics.</p></div>
          )}

          {data.length > 0 && (
            <div className="data-table-card">
              <h3>Live Data Grid</h3>
              <div className="table-responsive">
                <table>
                  <thead>
                    <tr><th>Name</th><th>Type</th><th>Pressure</th><th>Temp</th><th>Health Status</th></tr>
                  </thead>
                  <tbody>
                    {data.map((row, idx) => (
                      <tr key={idx}>
                        <td>{row['Equipment Name'] || row.name}</td>
                        <td>{row['Type'] || row.type}</td>
                        <td>{row['Pressure'] || row.pressure}</td>
                        <td>{row['Temperature'] || row.temp}</td>
                        <td><span className={`badge ${row.Status}`}>{row.Status}</span></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}

export default App;
